#!/usr/bin/python

import numpy as np
import matplotlib.pyplot as plt


def _GetMinFftSize(signal_length):
  return int(2 ** np.ceil(np.log2(signal_length)))

N_x = int(7.31 * 16000) 
B_array = np.arange(100, N_x, 10) # block_size
M = 2000

Mult_array = np.zeros(np.shape(B_array))

index = 0
for B in B_array:
  N = _GetMinFftSize(B + M - 1)
  #mult =  np.ceil(N_x / B) * (4 * N * np.log2(N) + 4 * N)
  mult =  np.ceil(N_x / B) *  N  ( np.log2(N)  + 1)
  Mult_array[index] = mult
  index = index + 1



print (np.shape(Mult_array))
print (np.shape(B_array))

plt.plot(B_array, Mult_array)
plt.show()
